name: swc-python-novice-gapminder-es
channels:
  - nodefaults
  - conda-forge
dependencies:
  # - c-compiler
  # - compilers
  # - cxx-compiler
  # - ruby
  - rb-jekyll
  - rb-kramdown >=2.1.0,<2.2
  - rb-kramdown-parser-gfm
